add token to port-f step
Signed-off-by: jcullina <jcullina@redhat.com>

diff --git a/.tekton/jen-port-forward.yaml b/.tekton/jen-port-forward.yaml
--- a/.tekton/jen-port-forward.yaml
+++ b/.tekton/jen-port-forward.yaml
@@ -211,7 +211,12 @@ spec:
               valueFrom:
                 secretKeyRef:
                   name: "$(tasks.provision-env.results.secretRef)"
-                  key: kubeconfig          
+                  key: kubeconfig
+            - name: OCM_TOKEN
+              valueFrom:
+                secretKeyRef:
+                  name: ocm
+                  key: ocmtoken          
           ports:
             - containerPort: 8000
           script: |
@@ -220,13 +225,18 @@ spec:
             cat <<< "$KUBECONFIG_VALUE" > /tmp/cfg
             export KUBECONFIG=/tmp/cfg
 
+            wget -O /tmp/ocm https://github.com/openshift-online/ocm-cli/releases/download/v0.1.65/ocm-linux-amd64
+            chmod +x /tmp/ocm
+            /tmp/ocm login --token=${OCM_TOKEN} --url=http://127.0.0.1:8000 --debug
+
             echo "Starting port-forward for service/trex on port 8000..."
             # Run port-forward in the background and log its output
             oc port-forward --kubeconfig /tmp/cfg svc/trex 8000:8000 &
-            sleep 20 
-
-            echo "Checking /tekton/scripts directory:"
-            ls -la /tekton/scripts 
+            sleep 20
+            if ! curl -s http://127.0.0.1:8000/api/rh-trex/v1/dinosaurs; then
+              echo "Port-forwarding failed or service unavailable."
+              exit 1
+            fi
         steps:
           - name: get-url
             image: registry.redhat.io/openshift4/ose-cli:latest
